#!/usr/bin/env python3
"""
This file contains utility functions.
"""
# Built-in
import os
import shutil
import warnings

# Dependencies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import binned_statistic
import smbhb as smbhb

#--------------------------------------------------------------#
#                       PUBLIC FUNCTIONS                       #
#--------------------------------------------------------------#

def day2sec():
    """Return 1 day in seconds.
    """
    return 86400


def year2sec():
    """Return 1 year in seconds.
    """
    return 31556926


def year2day():
    """Return 1 year in days.
    """
    return year2sec() / day2sec()


def quarter():
    """Return 1 mission quarter in days.
    """    
    return year2sec() / (4 * day2sec())


def rng(seed=None):
    """Initialise RNG and use seed for randomness.
    """
    if seed is None:
        return np.random.default_rng()
    else:
        return np.random.default_rng(seed=seed)        


def mag2flux(mag):
    """Convert relative magnitude to relative flux.
    """
    return 10**(-0.4*mag)

    
def bin_lc(df, bin_size=1):
    """Bin data wrt to the input time scale and cadence.
    """
    # Fetch time and flux
    time = df.time
    flux = df.flux
    # Bin light curve
    tdur = time.iloc[-1] - time.iloc[0]
    bins = round(tdur / bin_size)
    flux_bin, time_bin, _ = binned_statistic(time, flux, 'median', bins=bins)
    time_bin = time_bin[:-1] + np.diff(time_bin)[0]/2.
    # Bin flux errors if available
    if df.columns.str.startswith("flux_err").sum():
        flux_err = df.flux_err
        flux_err, _, _ = binned_statistic(time, flux_err, 'median', bins=bins)
        data = np.transpose([time_bin, flux_bin, flux_err])
        cols = ['time', 'flux', 'flux_err']
    else:
        data = np.transpose([time_bin, flux_bin])
        cols = ["time", "flux"]
    # Make sure to remove NaNs
    return pd.DataFrame(data, columns=cols).dropna()

        
def get_psd(time, tau, sigma):
    """Generate a red noise model from the PSD [ppm^2/microHz].

    Compute the mean power spectral density (PSD) corresponding to the 
    red noise time series that is generated by model_red_noise().

    Parameters
    ----------
    freq : ndarray
        frequency points of the PSD.
    timescale : float
        Also know as tau for red noise signal [inverse of freq].
     varscale : float
        Also known as sigma in red noise signal.

    Returns
    -------
    psd : ndarray
        Power spectral density (PSD) in units: [sigma]^2/[freq]
    """
    # Compute frequency array
    freq = 1 / time
    # Make sure tau and sigma is arrays
    if isinstance(tau, list):
        tau = np.array(tau)
    if isinstance(sigma, list):
        sigma = np.array(sigma)
    # Compute PSD time series
    psd = np.zeros_like(freq)
    for n in range(len(tau)):
        sigma = sigma[n]
        tau  = tau[n]
        psd += tau**2 * sigma**2 / (1 + (2 * np.pi * freq * tau)**2)
    return psd


def load_result(filename):
    """Load- binary file into a dictorionary.
    """
    return np.load(filename, allow_pickle=True).item()


def get_percentiles(result, pt_low=16, pt_upp=84, latex=False):
    """Fetch posterior per centiles.
    """
    table = {}
    samples = result['samples']
    names   = result['names']
    for n in names:
        sample  = samples[n]
        val     = np.percentile(sample, 50, axis=0)
        val_low = np.percentile(sample, pt_low, axis=0) - val
        val_upp = np.percentile(sample, pt_upp, axis=0) - val
        table.update({f'{n}':val, f'{n}_low':val_low, f'{n}_upp':val_upp})
        if latex:
            print(n,': pmx','{',f'{val:.4f}','}{',f'{val_low:.4f}','}{',f'{val_upp:.4f}','}')
    return table


# def fetch_gaia_info(df, NED=False):
#     """Fetch Gaia info for each source in data frame.
#     Use NASA/IPAC Extragalactic Database (NED).
#     """
#     for i in range(df.shape[0]):
#         di = df.reset_index(drop=True).loc[i]
#         if NED:
#             ra, dec = di.RA, di.Dec
#         else:
#             ra, dec = di.ra, di.dec
#         # FIXME sq is not loaded
#         dx = sq.gaiaQueryCone(ra, dec, radius=0.001, mag_max=21)
#         if dx.shape[0] > 1:
#             dx = dx[dx.dis == 0]
#         if i == 0:
#             dq = dx
#         else:
#             dq = pd.concat((dq, dx))
            
#     # Alter data frame
#     dq = dq.reset_index(drop=True)
#     dq = dq.drop(columns='dis')
#     if NED:
#         dq.insert(0, 'source', df['Object Name'])
#         dq['z'] = df['Redshift (z)']
#     return dq 
